#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running eslint...\n"
yarn lint
echo "\nRunning prettier...\n"
npx prettier --write "**/*.{js,jsx,ts,tsx,css,scss}"
echo "\nRunning typescript compiler...\n"
npx tsc
echo "\nRunning tests...\n"
yarn test --watchAll=false
